modLoader = "javafml"
loaderVersion = "[47,)"
license = "Terrarium License"
issueTrackerURL = "https://github.com/terrarium-earth/chipped/issues"

[[mods]]
modId = "chipped"
version = "${version}"
displayName = "Chipped"
displayURL = "https://modrinth.com/mod/chipped"
logoFile = "icon.png"
authors = "Alex Nijjar, Grimbop, Kekie6, ThatGravyBoat"
credits = "CodexAdrian, Facu, Marc-IceBlade, MsRandom"
description = "Every block needs a friend!"

[[dependencies.chipped]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chipped]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chipped]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chipped]]
modId = "athena"
mandatory = true
versionRange = "[3.0.0,)"
ordering = "NONE"
side = "CLIENT"