modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/CookieCNetwork/Chipped/issues"
[[mods]]
modId="chipped"
version="${file.jarVersion}"
logoFile="Chipped_Logo.png"
displayName="Chipped"
credits="Code: Grim, Inforno. Textures/Art: Kekie6, BrotherEarth967, Math, SunsetSoup, Valila, ArtistMonster"
authors="grimbo"
description='''
'''

[[dependencies.chipped]]
modId="ctm"
mandatory=false
versionRange="MC1.16.1-1.1.0.1,)"
ordering="NONE"
side="CLIENT"